#! /usr/bin/env ash
_usage() {
	cat << EOF
Usage: telfifo {enable|disable} FIFO
       telfifo list
EOF
}
SELFAUTODIR="${0%/*}"
case $SELFAUTODIR in [^/]*) SELFAUTODIR="$PWD/$SELFAUTODIR";; esac

. "${TELEFON_CFG:=$SELFAUTODIR/../../etc/default.telefon/system.cfg}"

if [ ! -d "$TELEFON_FIFODIR" ]; then
	mkdir -p "$TELEFON_FIFODIR"
fi

_enable() {
	local FIFO="$1"
	if [ -d "$FIFO" ]; then
		echo "$FIFO is a directory" >&2
		exit 1
	fi
	if [ ! -w "$FIFO" ]; then
		echo "$FIFO is not writable" >&2
		exit 1
	fi
	# 'sed -e q' instead of inavailable 'head -1'
	let id="$(ls -r "$TELEFON_FIFODIR" | sed -e q) + 1"
	ln -s "$FIFO" "$TELEFON_FIFODIR/$id"
}
_disable() {
	local FIFO="$1"
	for fifo in "$TELEFON_FIFODIR"/*; do
		[ -e "$fifo" ] || continue
		if [ "$FIFO" = "$(_readlink "$fifo")" ]; then
			rm "$fifo"
		fi
	done
}
_readlink() {
	local path="$(ls -l "$1")"
	echo "${path#*-> }"
}

case "$1" in
	enable|disable)
		if [ $# -lt 2 ]; then
			_usage >&2
			exit 1
		fi
		case "$2" in
			/*) FIFO="$2" ;;
			*)  FIFO="$PWD/$2" ;;
		esac
		;;
esac
case "$1" in
	enable)
		_disable "$FIFO"
		_enable "$FIFO"
		"$TELEFON_RC" reload
		;;
	disable)
		_disable "$FIFO"
		"$TELEFON_RC" reload
		;;
	list)
		ls -l "$TELEFON_FIFODIR" |
		sed -e '
			/->/! d
			s/^\(.*\)\([[:alnum:]_]\+\)[[:space:]]\+->[[:space:]]\+\(.*\)$/\2 \3/
		'
		;;
	*)
		_usage >&2
		exit 1
		;;
esac
