#! /usr/bin/env ash
##
## Callmonitor for Fritz!Box (telefon)
## 
## Copyright (C) 2005--2006  Andreas Bühmann <buehmann@users.berlios.de>
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
## 
## http://developer.berlios.de/projects/callmonitor/
##
_usage() {
#<
    cat << EOF
Usage: telfifo {enable|disable} FIFO
       telfifo list
EOF
#>
}
SELFAUTODIR="${0%/*}"
case $SELFAUTODIR in [^/]*) SELFAUTODIR="$PWD/$SELFAUTODIR";; esac

. "${TELEFON_CFG:=$SELFAUTODIR/../../etc/default.telefon/system.cfg}"
export PATH="$TELEFON_PATH"

if [ ! -d "$TELEFON_FIFODIR" ]; then
    mkdir -p "$TELEFON_FIFODIR"
fi

_enable() {
    local FIFO="$1"
    if [ -d "$FIFO" ]; then
	echo "$FIFO is a directory" >&2
	exit 1
    fi
    if [ ! -w "$FIFO" ]; then
	echo "$FIFO is not writable" >&2
	exit 1
    fi
    # 'sed -e q' instead of inavailable 'head -1'
    let id="$(ls -r "$TELEFON_FIFODIR" | sed -e q) + 1"
    ln -s "$FIFO" "$TELEFON_FIFODIR/$id"
}
_disable() {
    local FIFO="$1"
    for fifo in "$TELEFON_FIFODIR"/*; do
	[ -e "$fifo" ] || continue
	if [ "$FIFO" = "$(_readlink "$fifo")" ]; then
	    rm "$fifo"
	fi
    done
}
_readlink() {
    local path="$(ls -l "$1")"
    echo "${path#*-> }"
}

case "$1" in
    enable|disable)
	if [ $# -lt 2 ]; then
	    _usage >&2
	    exit 1
	fi
	case "$2" in
	    /*) FIFO="$2" ;;
	    *)  FIFO="$PWD/$2" ;;
	esac
	;;
esac
case "$1" in
    enable)
	_disable "$FIFO"
	_enable "$FIFO"
	"$TELEFON_RC" reload
	;;
    disable)
	_disable "$FIFO"
	"$TELEFON_RC" reload
	;;
    list)
	ls -l "$TELEFON_FIFODIR" |
	sed -e '
	    /->/! d
	    s/^\(.*\)\([[:alnum:]_]\+\)[[:space:]]\+->[[:space:]]\+\(.*\)$/\2 \3/
	'
	;;
    *)
	_usage >&2
	exit 1
	;;
esac
