#! /bin/sh
##
## Callmonitor for Fritz!Box (common)
## 
## Copyright (C) 2005--2006  Andreas Bühmann <buehmann@users.berlios.de>
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
## 
## http://developer.berlios.de/projects/callmonitor/
##
ARCHIVE="${1##*/}"
case $ARCHIVE in
    *-*-root.tar) ;;
    *)
	echo "Usage: $0 <package>-<version>-root.tar" >&2
	exit 1
    ;;
esac
PKGVER="${ARCHIVE%-root.tar}"
VER="${PKGVER##*-}"
PKG="${PKGVER%-$VER}"
MOD_ROOT='/var/mod'
if [ ! -d "$MOD_ROOT" ]; then
    mkdir -p "$MOD_ROOT"
fi
tar xf "$ARCHIVE" -C "$MOD_ROOT"
if [ -x "$MOD_ROOT/etc/init.d/rc.$PKG" ]; then
    "$MOD_ROOT/etc/init.d/rc.$PKG" load
fi
mkdir -p "$MOD_ROOT/pkg"
ln -s .. "$MOD_ROOT/pkg/$PKG"
